version: "2"
services:
  fpm:
    build: PHP7fpm
    # restart: always
    volumes:
      - ./:/var/app
    environment:
      - DATABASE_URL=mysql://root:root@cb_db/api_db
      - ENV=dev

    ports:
      - "9000:9000"
    links:
      - mysql

    container_name: cb_server

  nginx:
    image: nginx
    # restart: always
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./Logs/Nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - fpm
    container_name: cb_nginx

  mysql:
    image: mysql:5.7
    #restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api_db
    volumes:
      - ./data/db:/var/lib/mysql
    container_name: cb_db
